### ISSUE TITLE
On timeout Response answer is empty

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [yyfrankyy/dns-over-http2#24]
if timeout occurs, for whatever reason.
Response code is noerror with empty answer. 
make dns asking Application understand

> Response received from 127.0.0.1:
> Answer section:
> No A-Records found for github.com

because res.end(); is still called After  if (output && output.Answer) {}

can there be added something like
.on('timeout',     RETRY Request? 
than  respond with res.end(); inside end of "if (output && output.Answer) {}"

**Comment by yyfrankyy** [comment]
HI, I added another `responseCode=2` if any error occurs before `res.end()`.

https://github.com/yyfrankyy/h2dns/commit/98ccc8806a6e249ebc92d8e59cc6a1df215d2181#diff-607692532d26968b9251fefed20a6b15R141

this should be fixed in a way.

retry is a good suggestion but the strategy needs more discussion, such as retry interval, retry times, etc..

**Comment by yyfrankyy** [comment]
this is good library for retrying https://www.npmjs.com/package/retry

**Comment by yyfrankyy** [comment]
retry is introduced in https://github.com/yyfrankyy/h2dns/commit/7335318702e0268f12e9c9562dd95d307069940e
